package br.compra.telas;

import br.compra.dao.ProdutoDao;
import br.compra.getset.ProdutoGetSet;
import br.compra.listeners.AddProdListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AddProdutoRequisicao extends javax.swing.JInternalFrame {

    private final DefaultTableModel model2;
    private ProdutoGetSet prod;
    private List<ProdutoGetSet> lis;
    private RequisicaoCompra req;

    public AddProdutoRequisicao() {
        initComponents();

        btn_Adicionar.addActionListener(new AddProdListener(this));
        btn_Finalizar.addActionListener(new AddProdListener(this));
        btn_Remover.addActionListener(new AddProdListener(this));
        model2 = (DefaultTableModel) tabela_Add.getModel();
        this.setFrameIcon(new ImageIcon("src/br/compra/icones/installer_box.png"));

    }

    public void atualizaLista() {
        ProdutoDao pDao = new ProdutoDao();

        List<ProdutoGetSet> lisP = pDao.Read();

        DefaultTableModel model = (DefaultTableModel) tabela_produtos.getModel();
        model.setNumRows(0);

        for (int i = 0; i < lisP.size(); i++) {

            model.addRow(new Object[]{lisP.get(i).getCodigo(), lisP.get(i).getNome(), 5});

        }
    }

    public void AddRequisicao() {
        int linha = tabela_produtos.getSelectedRow();

        String cod = (String) tabela_produtos.getValueAt(linha, 0);
        String prodt = (String) tabela_produtos.getValueAt(linha, 1);

        String quantidade = "";
        while(quantidade.length() <  1){
        quantidade = JOptionPane.showInputDialog("Informe a quantidade");
            
        }

        model2.addRow(new Object[]{cod, prodt, quantidade});
    }

    public void RemoveRequisicao() {

        if (tabela_Add.getSelectedRow() != -1) {
            model2.removeRow(tabela_Add.getSelectedRow());
        }

    }

    public void setReq(RequisicaoCompra req) {
        this.req = req;
    }

    public void Finaliza() {
        lis = new ArrayList<>();

        while (model2.getRowCount() > 0) {
            prod = new ProdutoGetSet();
            String cod = (String) model2.getValueAt(0, 0);
            String Prod = (String) model2.getValueAt(0, 1);
            String Quant = (String) model2.getValueAt(0, 2);

            prod.setCodigo(cod);
            prod.setNome(Prod);
            prod.setquant(Quant);

            lis.add(prod);
            model2.removeRow(0);

        }
        req.setlis(lis);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_Produtos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_produtos = new javax.swing.JTable();
        jpanel_Add = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Add = new javax.swing.JTable();
        btn_Remover = new javax.swing.JButton();
        btn_Adicionar = new javax.swing.JButton();
        btn_Finalizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Adicionar Produtos");

        jpanel_Produtos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estoque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jpanel_Produtos.setPreferredSize(new java.awt.Dimension(430, 340));

        tabela_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_produtos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabela_produtos);
        if (tabela_produtos.getColumnModel().getColumnCount() > 0) {
            tabela_produtos.getColumnModel().getColumn(0).setResizable(false);
            tabela_produtos.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanel_ProdutosLayout = new javax.swing.GroupLayout(jpanel_Produtos);
        jpanel_Produtos.setLayout(jpanel_ProdutosLayout);
        jpanel_ProdutosLayout.setHorizontalGroup(
            jpanel_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_ProdutosLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_ProdutosLayout.setVerticalGroup(
            jpanel_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpanel_Add.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos Solicitados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jpanel_Add.setPreferredSize(new java.awt.Dimension(430, 340));

        tabela_Add.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Add.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela_Add);
        if (tabela_Add.getColumnModel().getColumnCount() > 0) {
            tabela_Add.getColumnModel().getColumn(0).setResizable(false);
            tabela_Add.getColumnModel().getColumn(1).setResizable(false);
            tabela_Add.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jpanel_AddLayout = new javax.swing.GroupLayout(jpanel_Add);
        jpanel_Add.setLayout(jpanel_AddLayout);
        jpanel_AddLayout.setHorizontalGroup(
            jpanel_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpanel_AddLayout.setVerticalGroup(
            jpanel_AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );

        btn_Remover.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_Remover.setForeground(new java.awt.Color(51, 51, 55));
        btn_Remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/compra/icones/delete.png"))); // NOI18N
        btn_Remover.setText("Remover");
        btn_Remover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_Adicionar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_Adicionar.setForeground(new java.awt.Color(51, 51, 55));
        btn_Adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/compra/icones/arrow_right.png"))); // NOI18N
        btn_Adicionar.setText("Adicionar");
        btn_Adicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_Finalizar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_Finalizar.setForeground(new java.awt.Color(51, 51, 55));
        btn_Finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/compra/icones/box_closed.png"))); // NOI18N
        btn_Finalizar.setText("Finalizar");
        btn_Finalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Remover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Adicionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btn_Finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jpanel_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btn_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpanel_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Finalizar;
    private javax.swing.JButton btn_Remover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpanel_Add;
    private javax.swing.JPanel jpanel_Produtos;
    private javax.swing.JTable tabela_Add;
    private javax.swing.JTable tabela_produtos;
    // End of variables declaration//GEN-END:variables
}
